# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_5/bd_1953_c_shift_ram_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1953_c_shift_ram_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_5/bd_1953_c_shift_ram_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1953_c_shift_ram_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
