# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/SFP_M_axi_10g_ethernet/SFP_M_axi_10g_ethernet.xci
# IP: The module: 'SFP_M_axi_10g_ethernet' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: ip/SFP_M_axi_10g_ethernet/bd_0/bd_c84c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c || ORIG_REF_NAME==bd_c84c} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_0/bd_c84c_xmac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_xmac_0 || ORIG_REF_NAME==bd_c84c_xmac_0} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/bd_c84c_xpcs_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_xpcs_0 || ORIG_REF_NAME==bd_c84c_xpcs_0} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_2/bd_c84c_prtad_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_prtad_driver_0 || ORIG_REF_NAME==bd_c84c_prtad_driver_0} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_3/bd_c84c_dcm_locked_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_dcm_locked_driver_0 || ORIG_REF_NAME==bd_c84c_dcm_locked_driver_0} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_4/bd_c84c_pma_pmd_type_driver_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_c84c_pma_pmd_type_driver_0} -quiet] -quiet

# XDC: ip/SFP_M_axi_10g_ethernet/synth/SFP_M_axi_10g_ethernet_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SFP_M_axi_10g_ethernet'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SFP_M_axi_10g_ethernet/bd_0/bd_c84c_ooc.xdc

# IP: ip/SFP_M_axi_10g_ethernet/SFP_M_axi_10g_ethernet.xci
# IP: The module: 'SFP_M_axi_10g_ethernet' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: ip/SFP_M_axi_10g_ethernet/bd_0/bd_c84c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c || ORIG_REF_NAME==bd_c84c} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_0/bd_c84c_xmac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_xmac_0 || ORIG_REF_NAME==bd_c84c_xmac_0} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/bd_c84c_xpcs_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_xpcs_0 || ORIG_REF_NAME==bd_c84c_xpcs_0} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_2/bd_c84c_prtad_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_prtad_driver_0 || ORIG_REF_NAME==bd_c84c_prtad_driver_0} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_3/bd_c84c_dcm_locked_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_dcm_locked_driver_0 || ORIG_REF_NAME==bd_c84c_dcm_locked_driver_0} -quiet] -quiet

# IP: ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_4/bd_c84c_pma_pmd_type_driver_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c84c_pma_pmd_type_driver_0 || ORIG_REF_NAME==bd_c84c_pma_pmd_type_driver_0} -quiet] -quiet

# XDC: ip/SFP_M_axi_10g_ethernet/synth/SFP_M_axi_10g_ethernet_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SFP_M_axi_10g_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SFP_M_axi_10g_ethernet/bd_0/bd_c84c_ooc.xdc
