# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/SGMII_S_axi_ethernet/SGMII_S_axi_ethernet.xci
# IP: The module: 'SGMII_S_axi_ethernet' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: ip/SGMII_S_axi_ethernet/bd_0/bd_1953.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953 || ORIG_REF_NAME==bd_1953} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_0/bd_1953_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_mac_0 || ORIG_REF_NAME==bd_1953_mac_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_1/bd_1953_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_pcs_pma_0 || ORIG_REF_NAME==bd_1953_pcs_pma_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_2/bd_1953_xlconstant_phyadd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_1953_xlconstant_phyadd_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_3/bd_1953_xlconstant_config_vec_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_xlconstant_config_vec_0 || ORIG_REF_NAME==bd_1953_xlconstant_config_vec_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_4/bd_1953_xlconstant_config_val_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_xlconstant_config_val_0 || ORIG_REF_NAME==bd_1953_xlconstant_config_val_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_5/bd_1953_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_c_shift_ram_0_0 || ORIG_REF_NAME==bd_1953_c_shift_ram_0_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_6/bd_1953_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_c_counter_binary_0_0 || ORIG_REF_NAME==bd_1953_c_counter_binary_0_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_7/bd_1953_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_xlconstant_0_0 || ORIG_REF_NAME==bd_1953_xlconstant_0_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_8/bd_1953_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_util_vector_logic_0_0 || ORIG_REF_NAME==bd_1953_util_vector_logic_0_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_9/bd_1953_reset_inv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_reset_inv_0 || ORIG_REF_NAME==bd_1953_reset_inv_0} -quiet] -quiet

# XDC: ip/SGMII_S_axi_ethernet/SGMII_S_axi_ethernet_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SGMII_S_axi_ethernet'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SGMII_S_axi_ethernet/synth/SGMII_S_axi_ethernet_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SGMII_S_axi_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SGMII_S_axi_ethernet/bd_0/bd_1953_ooc.xdc

# IP: ip/SGMII_S_axi_ethernet/SGMII_S_axi_ethernet.xci
# IP: The module: 'SGMII_S_axi_ethernet' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: ip/SGMII_S_axi_ethernet/bd_0/bd_1953.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953 || ORIG_REF_NAME==bd_1953} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_0/bd_1953_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_mac_0 || ORIG_REF_NAME==bd_1953_mac_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_1/bd_1953_pcs_pma_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_pcs_pma_0 || ORIG_REF_NAME==bd_1953_pcs_pma_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_2/bd_1953_xlconstant_phyadd_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_1953_xlconstant_phyadd_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_3/bd_1953_xlconstant_config_vec_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_xlconstant_config_vec_0 || ORIG_REF_NAME==bd_1953_xlconstant_config_vec_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_4/bd_1953_xlconstant_config_val_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_xlconstant_config_val_0 || ORIG_REF_NAME==bd_1953_xlconstant_config_val_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_5/bd_1953_c_shift_ram_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_c_shift_ram_0_0 || ORIG_REF_NAME==bd_1953_c_shift_ram_0_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_6/bd_1953_c_counter_binary_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_c_counter_binary_0_0 || ORIG_REF_NAME==bd_1953_c_counter_binary_0_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_7/bd_1953_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_xlconstant_0_0 || ORIG_REF_NAME==bd_1953_xlconstant_0_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_8/bd_1953_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_util_vector_logic_0_0 || ORIG_REF_NAME==bd_1953_util_vector_logic_0_0} -quiet] -quiet

# IP: ip/SGMII_S_axi_ethernet/bd_0/ip/ip_9/bd_1953_reset_inv_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_1953_reset_inv_0 || ORIG_REF_NAME==bd_1953_reset_inv_0} -quiet] -quiet

# XDC: ip/SGMII_S_axi_ethernet/SGMII_S_axi_ethernet_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SGMII_S_axi_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SGMII_S_axi_ethernet/synth/SGMII_S_axi_ethernet_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SGMII_S_axi_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SGMII_S_axi_ethernet/bd_0/bd_1953_ooc.xdc
