# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/DELAY_PLL/DELAY_PLL.xci
# IP: The module: 'DELAY_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/DELAY_PLL/DELAY_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DELAY_PLL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/DELAY_PLL/DELAY_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'DELAY_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/DELAY_PLL/DELAY_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DELAY_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: ip/DELAY_PLL/DELAY_PLL.xci
# IP: The module: 'DELAY_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/DELAY_PLL/DELAY_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DELAY_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/DELAY_PLL/DELAY_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'DELAY_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/DELAY_PLL/DELAY_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DELAY_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
