# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/project/DN_NewNP/NewNP_PJ/user_rtl/New_NP.xdc

# TCL: imports/project/HXT_Public_IP/UnrelatedFpga_ip/Misc/SyncSig/SyncSig.tcl

# TCL: imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamAsyncFifo/ParamAsyncFifo.tcl

# TCL: imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamSdpram/ParamSdpram.tcl

# TCL: imports/project/HXT_Public_IP/SpecificDedicateCode/SyncTimeCDC/SyncTimeCDC.tcl

# IP: ip/SGMII_M_axi_ethernet/SGMII_M_axi_ethernet.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SGMII_M_axi_ethernet || ORIG_REF_NAME==SGMII_M_axi_ethernet} -quiet] -quiet

# Block Designs: ip/SGMII_M_axi_ethernet/bd_0/bd_074d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d || ORIG_REF_NAME==bd_074d} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_0/bd_074d_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_mac_0 || ORIG_REF_NAME==bd_074d_mac_0} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_1/bd_074d_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_pcs_pma_0 || ORIG_REF_NAME==bd_074d_pcs_pma_0} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_2/bd_074d_xlconstant_phyadd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_074d_xlconstant_phyadd_0} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_3/bd_074d_xlconstant_config_vec_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_xlconstant_config_vec_0 || ORIG_REF_NAME==bd_074d_xlconstant_config_vec_0} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_4/bd_074d_xlconstant_config_val_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_xlconstant_config_val_0 || ORIG_REF_NAME==bd_074d_xlconstant_config_val_0} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_5/bd_074d_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_c_shift_ram_0_0 || ORIG_REF_NAME==bd_074d_c_shift_ram_0_0} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_6/bd_074d_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_c_counter_binary_0_0 || ORIG_REF_NAME==bd_074d_c_counter_binary_0_0} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_7/bd_074d_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_xlconstant_0_0 || ORIG_REF_NAME==bd_074d_xlconstant_0_0} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_8/bd_074d_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_util_vector_logic_0_0 || ORIG_REF_NAME==bd_074d_util_vector_logic_0_0} -quiet] -quiet

# IP: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_9/bd_074d_reset_inv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_074d_reset_inv_0 || ORIG_REF_NAME==bd_074d_reset_inv_0} -quiet] -quiet

# XDC: ip/SGMII_M_axi_ethernet/SGMII_M_axi_ethernet_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SGMII_M_axi_ethernet || ORIG_REF_NAME==SGMII_M_axi_ethernet} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/SGMII_M_axi_ethernet/synth/SGMII_M_axi_ethernet_ooc.xdc

# XDC: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_0/synth/bd_074d_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074d_mac_0 || ORIG_REF_NAME==bd_074d_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_0/synth/bd_074d_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074d_mac_0 || ORIG_REF_NAME==bd_074d_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_0/synth/bd_074d_mac_0_ooc.xdc

# XDC: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_0/synth/bd_074d_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074d_mac_0 || ORIG_REF_NAME==bd_074d_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_1/bd_074d_pcs_pma_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074d_pcs_pma_0 || ORIG_REF_NAME==bd_074d_pcs_pma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_1/synth/bd_074d_pcs_pma_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_074d_pcs_pma_0 || ORIG_REF_NAME==bd_074d_pcs_pma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/SGMII_M_axi_ethernet/bd_0/ip/ip_1/synth/bd_074d_pcs_pma_0_ooc.xdc

# XDC: ip/SGMII_M_axi_ethernet/bd_0/bd_074d_ooc.xdc
