# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.cache/wt [current_project]
set_property parent.project_path F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set src_rc [catch { 
  puts "source F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/utils_1/imports/process_control/synthesis_pre.tcl"
  source F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/utils_1/imports/process_control/synthesis_pre.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 error "$_RESULT"
  send_msg_id runtcl-2 error "sourcing script F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/utils_1/imports/process_control/synthesis_pre.tcl failed"
  return -code error
}
read_verilog -library xil_defaultlib {
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/ram_shell/ASFIFO_8_16.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/AXISByteExtract.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/AXISByteInsert.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/AXISDestSplit.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/AXISDisp.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/AXISFifoBuf.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/AXISFifoBuf/AXISFifoPktBuf.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/AXISFifoBuf/AXISFifoStrBuf.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/AXISMux.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/AXISRegBuf.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/AXISRegBuf/AXISRegProBuf.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/AXISRegBuf/AXISRegStdBuf.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/AXISWidthExt.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/AXISWidthSub.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/RCSWL/CBSOutputCtrl/CBSCfgMgmt.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/RCSWL/CBSOutputCtrl/CBSOutputCtrl.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/RCSWL/CBSOutputCtrl/CBSQueueCtrl.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/RCSWL/CBSOutputCtrl/CBSSendCtrl.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/TransShapSchEngine/CBSShapAlg.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/CPUSchCtrlEngine/CPULoadStateStatis.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/CPUSchCtrlEngine/CPURcvDisp.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/CPUSchCtrlEngine/CPUSchCtrlEngine.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/CPUSchCtrlEngine/CPUTransCtrl.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/CfgFmtCov.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/RCSWL/CBSOutputCtrl/CreditCal.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/DN_NewNP_Core.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/DataInvert.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/CPUSchCtrlEngine/DbgMgmtCtrl.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/FastSwitchModule/FastSwitchLookup.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/FastSwitchModule/FastSwitchModule.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/FastSwitchModule/FastSwitchMux.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/TransShapSchEngine/FlowMeter.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/CPUSchCtrlEngine/HCPHub.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/FastSwitchModule/IPv6FwdProc.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/TenGXS/Project/code/RTL/TenGXS_COMMON/xHCP/InputPktFormatConvert.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/LbExt.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/NetMeterEngine/NetTelMeterEngine.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/TenGXS/Project/code/RTL/TenGXS_COMMON/xHCP/OutputPktFormatConvert.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamAsyncFifo.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamSdpram.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamSyncFifo.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamTdpram.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamTdpram_rddly.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/DataPathProc/PktLineDet.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/TransShapSchEngine/RCPktClassify.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/RCSWL/RCPktPolic.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/RCSWL/CBSOutputCtrl/RCPktPriorDisp.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/LookupClassify/RegFastLookupUnit.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/Misc/RstExtend.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/SRv6FwdEngine/SRv6FwdEngine.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/SRv6FwdEngine/SRv6FwdProc.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/SRv6InputEngine/SRv6InputEngine.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/FastSwitchModule/SRv6KeyParser.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/SRv6OutputEngine/SRv6OutputEngine.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/SRv6InputEngine/SRv6RcvFmtCov.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/SRv6InputEngine/SRv6RcvPreParser.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/SRv6OutputEngine/SRv6TransFmtCov.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/Misc/SyncSig.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/SyncTimeCDC.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/CPUSchCtrlEngine/SysMgmtCtrl.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/NetMeterEngine/TeleMeterPktGen.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/TransShapSchEngine/TransShapSchEngine.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/network_management/ack_type_parse.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/address_dispatch.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/time_announcement/address_encode.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/ram_shell/afifo.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/ram_shell/afifo_gray_sync.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/ram_shell/afifo_sync_dff.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/ram_shell/afifo_top.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/BitVectorProc/binary2gray.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/BitVectorProc/binary2onehot.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/BitVectorProc/bitmap2onehot.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/opensync_mac/opensync_1gmac/clock_domain_cross.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/opensync_timing/clock_timing_and_correcting.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_hcp/command_encapsulate_hcp.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_inex/command_encapsulate_inex.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/cycle_control/command_parse_and_encapsulate_cc.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_hcp/command_parse_and_encapsulate_hcp.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_inex/command_parse_and_encapsulate_inex.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/opensync_timing/command_parse_and_encapsulate_ost.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_forward_table/command_parse_and_encapsulate_tft.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_hcp/command_parse_hcp.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/local_access_control/command_parse_and_encapsulate_inex/command_parse_inex.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/tsmp_transmit_control/controller_output_schedule.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/head_and_tail_discard/cross_clock_domain_hcp.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/cycle_control/cycle_control.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/cycle_control/cycle_start_generate.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/tsmp_transmit_control/fifo_overflow_protect.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/BitVectorProc/gray2binary.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/hardware_control_point.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/hcp_register_group.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/head_and_tail_add/head_and_tail_add.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/head_and_tail_discard/head_and_tail_discard.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/local_access_control/local_access_control.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/opensync_timing/local_cnt_timing.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/opensync_mac/opensync_1gmac/mac_process/mac_process.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_forward_table/mid_lookup_table.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/network_management/network_management.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/network_management/network_management_generate.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/network_management/network_management_parse.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/BitVectorProc/onehot2binary.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/BitVectorProc/onehot2prepostfix.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/opensync_mac/opensync_1gmac/opensync_dispatch_pit_compensate.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/opensync_protocol.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/opensync_mac/opensync_1gmac/opensync_receive_pit_record.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/opensync_timing/opensync_timing.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/packet_switch/packet_switch.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/packet_switch/pkt_dispatch.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/packet_switch/pkt_select.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/BitVectorProc/prior_grant.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/opensync_mac/opensync_1gmac/mac_process/receive_mac_process.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/cycle_control/syn_clk_process.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/time_announcement/time_announce.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/time_announcement/tnc_lookup_table.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/opensync_mac/opensync_1gmac/mac_process/transmit_mac_process.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/tsmp_agent.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_forward_table/tsmp_forward_table.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/tsmp_protocol_process.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/tsmp_transmit_control/tsmp_transmit_control.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/HXT_Public_IP/SpecificDedicateCode/xHCP/hardware_control_point/tsmp_agent/tunnel_frame_process.v
  F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/imports/project/DN_NewNP/NewNP_PJ/code/New_NP_TOP.v
}
read_ip -quiet F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/SGMII_M_axi_ethernet.xci
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/SGMII_M_axi_ethernet_board.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/synth/SGMII_M_axi_ethernet_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/bd_0/ip/ip_0/synth/bd_074d_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/bd_0/ip/ip_0/synth/bd_074d_mac_0.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/bd_0/ip/ip_0/synth/bd_074d_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/bd_0/ip/ip_0/synth/bd_074d_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/bd_0/ip/ip_1/bd_074d_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/bd_0/ip/ip_1/synth/bd_074d_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/bd_0/ip/ip_1/synth/bd_074d_pcs_pma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/sources_1/ip/SGMII_M_axi_ethernet/bd_0/bd_074d_ooc.xdc]

read_ip -quiet F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/DELAY_PLL/ip/DELAY_PLL/DELAY_PLL.xci
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/DELAY_PLL/ip/DELAY_PLL/DELAY_PLL_board.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/DELAY_PLL/ip/DELAY_PLL/DELAY_PLL.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/DELAY_PLL/ip/DELAY_PLL/DELAY_PLL_ooc.xdc]

read_ip -quiet F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/SFP_M_axi_10g_ethernet.xci
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/synth/SFP_M_axi_10g_ethernet_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_0/synth/bd_c84c_xmac_0.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_0/synth/bd_c84c_xmac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_0/synth/bd_c84c_xmac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/synth/bd_c84c_xpcs_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/synth/bd_c84c_xpcs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/synth/bd_c84c_xpcs_0.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/bd_c84c_ooc.xdc]

read_ip -quiet F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/SGMII_S_axi_ethernet.xci
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/SGMII_S_axi_ethernet_board.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/synth/SGMII_S_axi_ethernet_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_0/synth/bd_1953_mac_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_0/synth/bd_1953_mac_0.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_0/synth/bd_1953_mac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_0/synth/bd_1953_mac_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_1/bd_1953_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_1/synth/bd_1953_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_1/synth/bd_1953_pcs_pma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_5/bd_1953_c_shift_ram_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/ip/ip_6/bd_1953_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SGMII_S_axi_ethernet/ip/SGMII_S_axi_ethernet/bd_0/bd_1953_ooc.xdc]

read_ip -quiet F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SYS_PLL/ip/SYS_PLL/SYS_PLL.xci
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SYS_PLL/ip/SYS_PLL/SYS_PLL_board.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SYS_PLL/ip/SYS_PLL/SYS_PLL.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SYS_PLL/ip/SYS_PLL/SYS_PLL_ooc.xdc]

read_ip -quiet F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/rgmii_ethernet_mac_m.xci
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_board.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_clocks.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/DN_NewNP/NewNP_PJ/user_rtl/New_NP.xdc
set_property used_in_implementation false [get_files F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/DN_NewNP/NewNP_PJ/user_rtl/New_NP.xdc]

read_xdc -unmanaged F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/Misc/SyncSig/SyncSig.tcl
set_property used_in_implementation false [get_files F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/Misc/SyncSig/SyncSig.tcl]

read_xdc -unmanaged F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamAsyncFifo/ParamAsyncFifo.tcl
set_property used_in_implementation false [get_files F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamAsyncFifo/ParamAsyncFifo.tcl]

read_xdc -unmanaged F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamSdpram/ParamSdpram.tcl
set_property used_in_implementation false [get_files F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/HXT_Public_IP/UnrelatedFpga_ip/InternalMemory/ParamSdpram/ParamSdpram.tcl]

read_xdc -unmanaged F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/HXT_Public_IP/SpecificDedicateCode/SyncTimeCDC/SyncTimeCDC.tcl
set_property used_in_implementation false [get_files F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/constrs_1/imports/project/HXT_Public_IP/SpecificDedicateCode/SyncTimeCDC/SyncTimeCDC.tcl]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top New_NP_TOP -part xc7k325tffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef New_NP_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file New_NP_TOP_utilization_synth.rpt -pb New_NP_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
