# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/synth/bd_c84c_xpcs_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_c84c_xpcs_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/synth/bd_c84c_xpcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_c84c_xpcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/synth/bd_c84c_xpcs_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_c84c_xpcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/synth/bd_c84c_xpcs_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_c84c_xpcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/synth/bd_c84c_xpcs_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_c84c_xpcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/SFP_M_axi_10g_ethernet/ip/SFP_M_axi_10g_ethernet/bd_0/ip/ip_1/synth/bd_c84c_xpcs_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_c84c_xpcs_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
