# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/SYS_PLL/SYS_PLL.xci
# IP: The module: 'SYS_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/SYS_PLL/SYS_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYS_PLL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SYS_PLL/SYS_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYS_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SYS_PLL/SYS_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYS_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: ip/SYS_PLL/SYS_PLL.xci
# IP: The module: 'SYS_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/SYS_PLL/SYS_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYS_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SYS_PLL/SYS_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYS_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/SYS_PLL/SYS_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SYS_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
