# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/rgmii_ethernet_mac_m/rgmii_ethernet_mac_m.xci
# IP: The module: 'rgmii_ethernet_mac_m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgmii_ethernet_mac_m'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgmii_ethernet_mac_m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgmii_ethernet_mac_m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgmii_ethernet_mac_m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: ip/rgmii_ethernet_mac_m/rgmii_ethernet_mac_m.xci
# IP: The module: 'rgmii_ethernet_mac_m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgmii_ethernet_mac_m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgmii_ethernet_mac_m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgmii_ethernet_mac_m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgmii_ethernet_mac_m'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
