# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.runs/rgmii_ethernet_mac_m_synth_1/.Xil/Vivado-26600-LAPTOP-7FEMNP8M/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k325tffg676-2
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/hdl/avb {
      D:/vivado/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/vivado/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/hdl/avb {
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/hdl/tri_mode_ethernet_mac_v9_0_rfs.v
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/common/rgmii_ethernet_mac_m_block_reset_sync.v
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/common/rgmii_ethernet_mac_m_block_sync_block.v
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_clk_en_gen.v
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/physical/rgmii_ethernet_mac_m_rgmii_v2_0_if.v
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_block.v
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_support.v
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_support_clocking.v
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m_support_resets.v
      f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/synth/rgmii_ethernet_mac_m.v
    }
      rt::read_vhdl -lib xbip_utils_v3_0_9 f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_5 f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_5 f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_14 f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_lite_ipif_v3_0_4 f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib tri_mode_ethernet_mac_v9_0_13 f:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.srcs/rgmii_ethernet_mac_m/ip/rgmii_ethernet_mac_m/hdl/tri_mode_ethernet_mac_v9_0_rfs.vhd
      rt::read_vhdl -lib xpm D:/vivado/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top rgmii_ethernet_mac_m
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "F:/实验室/毕业论文/实验/np123/New_NP_PJ.xpr/New_NP_PJ/New_NP_PJ.runs/rgmii_ethernet_mac_m_synth_1/.Xil/Vivado-26600-LAPTOP-7FEMNP8M/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
